### ISSUE TITLE
Cannot Damage Trainer's Pokémobs

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#171]
#### Issue Description:
Pokémobs sent out by trainers cannot be damaged

#### What happens:
- If a Pokémob is sent out by a trainer, the player or the player's Pokémob will be unable to damage the trainer's
- The screen will either say the attack missed or isn't effective.

#### What you expected to happen:
- The player/player's Pokémob should cause damage.

#### Steps to reproduce:

1. Find a Trainer
2. Battle him/her.
...

____
#### Affected Versions:

- `Pokecube AIO: v2.0.0.i`
- `Minecraft: v1.14.4`
- `Forge: v28.1.116`

**Comment by WenXin20** [comment]
As a side note, trainers also spawn too often. 
Multiple trainers will also often send their Pokémobs out all at once.

**Comment by Thutmose** [comment]
I cannot seem to replicate this, maybe it is fixed in the current development environment, I will try to put an update in releases shortly

**Comment by WenXin20** [comment]
I'm still unable to do damage to a Trainer's Pokémob, either by punching or my own pokemobs. This was with version j.

**Comment by WenXin20** [comment]
But wild pokemobs I am able to damage.

**Comment by WenXin20** [comment]
Seems to be fixed
